### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by cdoney** [MeetMe/newrelic-plugin-agent#151]
Hi;

I was installing the New Relic plugin from MeetMe, and it looked to be going well, when I got "fatal error: Python.h: No such file or directory".  I need help debugging this error.

Thanks... Clark

NOTE:  I've included pertinent error msgs from the pip.log file below;

 gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/usr/local/nrplugins/newrelic_plugin_agent-1.1.0/build/pyyaml/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-nSCROa-record/install-record.txt:

> > > > > stuff <<<<<<

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o

ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

> > > > > stuff <<<<<<

Command /usr/bin/python -c "import setuptools;**file**='/usr/local/nrplugins/newrelic_plugin_agent-1.1.0/build/pyyaml/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-nSCROa-record/install-record.txt failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1093, in install
    requirement.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 566, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command /usr/bin/python -c "import setuptools;**file**='/usr/local/nrplugins/newrelic_plugin_agent-1.1.0/build/pyyaml/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-nSCROa-record/install-record.txt failed with error code 1
root@APRE01VMW01:/usr/local/nrplugins/newrelic_plugin_agent-1.1.0#

**Comment by rajamarni** [comment]
Hi,
I am trying to install pyyaml using the command 'sudo pip install pyyaml'
It is throws error 'ext/_yaml.c:16:20: fatal error: Python.h: No such file or directory'
I did yum install python-devel 
Even i am getting same error
Please help me 

Thanx in advance

**Comment by rdeva31** [comment]
Since this is a top hit on google, you might need to install `python3-dev` (on Debian based OSes) as well.

**Comment by descostesn** [comment]
had to do: sudo apt-get install python3.5-dev

**Comment by zchrissirhcz** [comment]
I'm late here, but I'd like to point out that, to cope with the same error, one should install python development package with proper (corresponding) python version. (I'm on ubuntu16.04)

Say, if I'm using python3.5, then I should do: `sudo apt install python3.5-dev`

However, if I just installed python3.6 for reason and changed the default python3 to point to python3.6, then for this `Python.h cannot find`  problem, I should do: `sudo apt install python3.6-dev`

**Comment by s3curityb3ast** [comment]
In my Case Python 3.7 I am able to solve this issue with below command 
```
aptitude install libpython3.7-dev 

or

apt-get install  libpython3.7-dev

```

**Comment by 0x78f1935** [comment]
For python3.7.5
`sudo apt-get install python3-dev`
did the trick for me

**Comment by firestonelib** [comment]
> Since this is a top hit on google, you might need to install `python3-dev` (on Debian based OSes) as well.

if your multiple python version, you need to specify your python version, for example:
apt-get install python3.6-dev

**Comment by THAVASIGTI** [comment]
try this
centos 7

python3 above version use

`sudo yum install python3-devel`

i try this command woking
