### ISSUE TITLE
plugin agent randomly stops sending data to newrelic

### ISSUE THREAD

**Issue by unsatcore** [MeetMe/newrelic-plugin-agent#163]
Once in a week or two plugin_agent stops collecting and sending data to newrelic.
The process is running, but does nothing.

I'm not sure about the reasons but at least once this coincided with a short network outage in a datacenter.

Here is a fresh log snippet.
Notice the gap between 2013-10-06 22:49:30 27993 and 2013-10-09 14:26:55 31165 (when plugin_agent was restarted manually):

INFO       2013-10-06 22:48:31 27993  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L122   : All stats processed in 1.24 seconds, next wake in 58.76
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : APC poll successful, completed in 0.00 seconds
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : Nginx poll successful, completed in 0.00 seconds
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : PostgreSQL poll successful, completed in 0.05 seconds
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : ApacheHTTPD poll successful, completed in 0.00 seconds
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        poll                      L328   : Polling RabbitMQ via http://localhost:15672/api
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        poll                      L348   : Polling complete in 0.10 seconds
INFO       2013-10-06 22:49:30 27993  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L209   : Sending 173 metrics to NewRelic
INFO       2013-10-09 14:26:55 31165  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : APC poll successful, completed in 0.03 seconds
INFO       2013-10-09 14:26:55 31165  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : Nginx poll successful, completed in 0.00 seconds
INFO       2013-10-09 14:26:56 31165  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : PostgreSQL poll successful, completed in 0.04 seconds
INFO       2013-10-09 14:26:56 31165  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L141   : ApacheHTTPD poll successful, completed in 0.00 seconds
INFO       2013-10-09 14:26:56 31165  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        poll                      L328   : Polling RabbitMQ via http://localhost:15672/api
INFO       2013-10-09 14:26:56 31165  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        poll                      L348   : Polling complete in 0.12 seconds
INFO       2013-10-09 14:26:56 31165  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L209   : Sending 206 metrics to NewRelic

**Comment by jarvinia** [comment]
INFO       2015-04-14 06:42:18,949 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   __init__                  L55    : Agent v1.3.0 initialized, Linux-3.2.0-70-generic-x86_64-with-glibc2.7 (Ubuntu 12.04 precise) CPython v2.7.3
INFO       2015-04-14 06:42:18,951 24806  MainProcess     MainThread helper.controller                             run                       L251   : newrelic-plugin-agent v2.4.1 started
INFO       2015-04-14 06:42:18,951 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: mongodb
INFO       2015-04-14 06:42:19,018 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : MongoDB poll successful, completed in 0.02 seconds
INFO       2015-04-14 06:42:19,019 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: redis
INFO       2015-04-14 06:42:19,020 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Redis
INFO       2015-04-14 06:42:19,022 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : Redis poll successful, completed in 0.00 seconds
INFO       2015-04-14 06:42:19,023 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: rabbitmq
INFO       2015-04-14 06:42:19,024 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        poll                      L354   : Polling RabbitMQ via http://localhost:15672/api
ERROR      2015-04-14 06:42:19,027 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        http_get                  L303   : Error fetching data from http://localhost:15672/api/channels: ('Connection aborted.', error(111, 'Connection refused'))
ERROR      2015-04-14 06:42:19,028 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        http_get                  L303   : Error fetching data from http://localhost:15672/api/nodes: ('Connection aborted.', error(111, 'Connection refused'))
ERROR      2015-04-14 06:42:19,029 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        http_get                  L303   : Error fetching data from http://localhost:15672/api/queues: ('Connection aborted.', error(111, 'Connection refused'))
INFO       2015-04-14 06:42:19,029 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.rabbitmq        poll                      L374   : Polling complete in 0.01 seconds
INFO       2015-04-14 06:42:19,029 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: nginx
ERROR      2015-04-14 06:42:19,033 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            http_get                  L349   : Error polling stats: ('Connection aborted.', error(111, 'Connection refused'))
ERROR      2015-04-14 06:42:19,033 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            error_message             L128   : Error collecting stats data from Nginx. Please check configuration and sure it conforms with YAML syntax
INFO       2015-04-14 06:42:19,033 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: memcached
INFO       2015-04-14 06:42:19,034 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling Memcached
ERROR      2015-04-14 06:42:19,035 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            connect                   L251   : Error connecting to Memcached: [Errno 111] Connection refused
ERROR      2015-04-14 06:42:19,035 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L284   : Memcached could not connect, skipping poll interval
INFO       2015-04-14 06:42:19,035 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: uwsgi
INFO       2015-04-14 06:42:19,036 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            poll                      L277   : Polling uWSGI
ERROR      2015-04-14 06:42:23,042 24806  MainProcess     MainThread newrelic_plugin_agent.plugins.base            error_message             L128   : Error collecting stats data from uWSGI. Please check configuration and sure it conforms with YAML syntax
INFO       2015-04-14 06:42:23,043 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L220   : Sending 124 metrics to NewRelic
INFO       2015-04-14 06:42:24,332 24806  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 5.38 seconds, next wake in 54 seconds
