### ISSUE TITLE
How to remove agent from newrelic dashboard

### ISSUE THREAD

**Issue by glmrenard** [MeetMe/newrelic-plugin-agent#176]
Hello

I did a test (successful) and now I want to remove the agent APC from my dashboard, how can I do that ?
![image](https://f.cloud.github.com/assets/1943276/1406653/69eb1b8e-3d57-11e3-966f-6a04f2c71225.png)

Thanks for answering me.
Best regards, Guillaume

**Comment by tuxmithun** [comment]
how do i bring back the plugin?

**Comment by coopr** [comment]
Hi @tuxmithun - I suggest you ask your question here https://discuss.newrelic.com/c/platform-plugins
