### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by iambibhas** [MeetMe/newrelic-plugin-agent#196]
I'm trying to launch it in background with following command - 

```
sudo -u newrelic newrelic_plugin_agent -c /etc/newrelic/newrelic_plugin_agent.cfg
```

But getting this error - 

```
Error starting /usr/local/bin/newrelic_plugin_agent: invalid literal for int() with base 10: ''
```

When I run in foreground with `-f` option, it runs fine. Anything I can look into to fix this?

**Comment by Van-Tien** [comment]
Does it work when we install newrelic-plugin-agent only ? I have same this issue but deleted did not help
