### ISSUE TITLE
Unable to import newrelic_plugin_agent.plugins.apache_httpd.ApacheHTTPD

### ISSUE THREAD

**Issue by dnichols4** [MeetMe/newrelic-plugin-agent#224]
When trying to start the newrelic_pluging_agent, we get the below error & I haven't been able to find any info on it.  Followed the install instructions, but my guess would be we're missing a module or something?

INFO       2014-01-26 10:57:09,674 5864   MainProcess     MainThread newrelic_plugin_agent.agent                   **init**                  L55    : Agent v1.2.2 initialized, Linux-2.6.32-358.23.2.el6.x86_64-x86_64-with-glibc2.2.5 (Red Hat Enterprise Linux Server 6.5 Santiago) CPython v2.6.6
INFO       2014-01-26 10:57:09,773 5875   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L260   : Enabling plugin: apache_httpd
ERROR      2014-01-26 10:57:09,774 5875   MainProcess     MainThread newrelic_plugin_agent.agent                   _get_plugin               L253   : Attempting to import newrelic_plugin_agent.plugins.apache_httpd.ApacheHTTPD
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/newrelic_plugin_agent/agent.py", line 249, in _get_plugin
  File "/usr/lib/python2.6/site-packages/importlib/__init__.py", line 37, in import_module
ImportError: No module named apache_httpd
ERROR      2014-01-26 10:57:09,774 5875   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L273   : Enabled plugin apache_httpd not available

**Comment by nisanthchunduru** [comment]
@dnichols4 I ran into this same issue while an init script https://github.com/SupportBee/newrelic-plugin-agent/blob/3d28c14edcbd89a690c1673d64bca6093a62d20a/etc/init.d/newrelic-plugin-agent.deb to start the daemon on our production servers

```
ERROR      2016-10-30 21:22:14,046 28187  MainProcess     MainThread newrelic_plugin_agent.agent                   _get_plugin               L258   : Attempting to import newrelic_plugin_agent.plugins.postgresql.PostgreSQL
Traceback (most recent call last):
  File "/root/newrelic-plugin-agent/newrelic_plugin_agent/agent.py", line 254, in _get_plugin
  File "/usr/local/lib/python2.6/dist-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
```

No such issues when I start the daemon in the foreground (using the `-f` option) though

Could you find the cause of the error?

**Comment by nisanthchunduru** [comment]
After two hours of careful debugging, I found the cause of the error.

I had installed the newrelic-plugin-agent as `root` user on our production servers

```
root@web1 ~ # pip install -e ~/newrelic-plugin-agent # Our fork of the newrelic-plugin-agent daemon
```

but hadn't updated the configuration file on one server. The plugin was daemonizing as the `newrelic` user instead of the `root` user

``` yaml
Daemon:
  user: newrelic
  pidfile: /var/run/newrelic/newrelic-plugin-agent.pid
```

I changed configuration file to

``` yaml
Daemon:
  user: root
  pidfile: /var/run/newrelic/newrelic-plugin-agent.pid
```

and the agent works fine now
