### ISSUE TITLE
elasticsearch overview page is blank

### ISSUE THREAD

**Issue by sarkis** [MeetMe/newrelic-plugin-agent#268]
I've set this up according to the installation instructions. It looks like data is going through as newrelic does show data, however, the initial Overview tab warns that the newrelic plugin agent is out of date. When I click on download, it sends me to the pypi page for newrelic-plugin-agent v1.2.3 (which is the one installed on my system).

Not sure if anyone else experiences similar issues with the overview page? I am assuming that newrelic has changed something on the web panel and this is now a bug with the plugin.

**Comment by genexp** [comment]
Hey guys - What did you end up doing here? I'm having the same problem, i'm sure it's something simple?

**Comment by chad-upton** [comment]
I had to upgrade ES to 1.4.2 or whatever is the latest.  The earlier versions don't work or at least I couldn't get it too.

**Comment by genexp** [comment]
Ahh thanks! We're stuck on 1.2 for now, this helped!
