### ISSUE TITLE
Migrate to str.format() for Python 3 compat

### ISSUE THREAD

**Issue by analytically** [MeetMe/newrelic-plugin-agent#286]
In setup.py you use `print '...' % package_dir`. This is incompatible with Python 3, and the str.format() syntax is compatible with Python 2 and 3.

http://stackoverflow.com/questions/13945749/string-formatting-in-python-3

**Comment by Nihisil** [comment]
@gmr Just co confirm. You still don't have plans to port this to Python 3? Or you're welcome to all pull-requests with Python 3 support features?
