### ISSUE TITLE
Adding Elasticsearch HTTP authentication functionality, re:for issue #262 #279

### ISSUE THREAD

**Issue by KludgeKML** [MeetMe/newrelic-plugin-agent#322]
HTTP basic authentication doesn't work with the elasticsearch plugin - because to get the _cluster/health data it uses requests.get directly, which means that it doesn't use the http_get and request_kwargs functions of HTTPStatsPlugin - and it's those functions which are responsible for putting in the username and password. 

The fix suggested in #279 is probably the simplest way of getting this functionality working. The code at the moment uses 

url = self.stats_url.replace(self.DEFAULT_PATH, '/_cluster/health')

to make a custom url for the cluster health and passes it to requests.get. Any other way of manipulating the url so that it could be used by http_get and request_kwargs seems like it would require temporarily manipulating the instance data in self.stats_url.

I'd like to suggest that the pull request from #279 be reexamined.

**Comment by gregavola** [comment]
I realize this is OLD - but I still can't figure out to use elasticsearch with http auth, there is no documentation provide, nor username/password in the config. Any help would be great!

**Comment by gmr** [comment]
It should just be ``username`` and ``password`` at the same level as all of the other options... i.e.:

```yaml
  elasticsearch:
    name: clustername
    host: localhost
    port: 9200
    username: foo
    password: bar
```

**Comment by gregavola** [comment]
If the password incudes "@" or "!" do you just do this:

```
 username: admin
 password: "@test!@"
```

How do add multiple clusters?

**Comment by KludgeKML** [comment]
@gmr : am I right in thinking this isn't yet in a release?

**Comment by gregavola** [comment]
@gmr any update here?

**Comment by morganwalker** [comment]
@gmr has this been released yet?  Looks like the last release was 5/2014, before this was fixed.
