### ISSUE TITLE
Incompatible with Heroku applications

### ISSUE THREAD

**Issue by joshfriend** [MeetMe/newrelic-plugin-agent#382]
Because of the way [`setup.py` depends on `$VIRTUAL_ENV`](https://github.com/MeetMe/newrelic-plugin-agent/blob/84f103a2cfbc8c44fbfdfd01f55b5279cbef1f41/setup.py#L5) to install example configuration files, installing the package in a Heroku app fails because `$VIRTUAL_ENV` is not set and most of the file system is read-only. The Heroku buildpack shows the following error:

```
error: could not create '/opt': Read-only file system
```

but doesn't reject the deploy push since the `pip install` seems to always return status code 0. The app then fails to boot properly because the above error cuts off the installation of other required packages.

Since the daemon won't run with the default config that gets put in `/opt` without modification, can the setup be changed to store the configuration with the rest of the egg data? Then the install wouldn't have to depend on `$VIRTUAL_ENV`, which is rather odd.

**Comment by gmr** [comment]
The dependency for checking if $VIRTUAL_ENV allows it to run and set the paths properly in virtualenv. Your change changes the behavior instead of allowing for an override, which would be my preference.
