### ISSUE TITLE
MongoDB Plugin Visualization Issue

### ISSUE THREAD

**Issue by luisdalves** [MeetMe/newrelic-plugin-agent#396]
Hi Guys,

I've installed mongodb plugin and I'm facing some issues in the graph visualization. I put the log in debug and I'm seeeing a json with all the data but is not graphing in NewRelic web.
When I go to plugins / mongodb / databases all graphs are empty.

This is my config:
  mongodb:
    name: mongo-server
    host: localhost
    port: 27017
    databases:
      - screen_names_production
      - tcompany_production

Has anybody a similar behavior?

Thanks

**Comment by genexp** [comment]
I'm seeing similar behavior for the Elastic plugin.  My log shows stats, if I put the daemon in debug mode I see that it has gathered them, but unfortunately graphs don't display.

**Comment by psychoche** [comment]
I have similar with Redis plugin. I see realtime info, but no graphs.
