### ISSUE TITLE
alternative to install plugin other than pip

### ISSUE THREAD

**Issue by adi8590** [MeetMe/newrelic-plugin-agent#469]
hello,

from documentation i see plugin installation is done through pip but is there an alternative to install the agent other than pip.

i was able to download the plugin zip file from below link and unzip it and update the cfg file. but i see there's no newrelic_plugin_agent script to start the agent.

https://github.com/MeetMe/newrelic-plugin-agent#installation-instructions

can you please assist.

Thanks

**Comment by adi8590** [comment]
Hello,

Any help on this? Need some clarification on installation to move forward.

Thanks

**Comment by StephenWeber** [comment]
If you have the project downloaded and unzipped, then from the project directory you should be able to run the following command to install the package without using pip:

`python setup.py install`

I have not tried this myself so I don't know what problems you may encounter. You definitely will need all the dependencies installed as well, they can be found in [the setup.py file](https://github.com/MeetMe/newrelic-plugin-agent/blob/master/setup.py#L15-L19)

This is standard usage of setuptools, so I'm not sure it belongs in this project's documentation.

**Comment by adi8590** [comment]
Thanks StephenWeber. 
The solution you provided worked. i had to download and install the pre-req in similar fashion before installing the newrelic agent.
