### ISSUE TITLE
Not seeing data or charts in newrelic

### ISSUE THREAD

**Issue by msenevir** [MeetMe/newrelic-plugin-agent#498]
The logs show that metrics are being sent:

```
INFO       2016-07-29 10:29:58,371 12295  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: postgresql
INFO       2016-07-29 10:29:58,402 12295  MainProcess     MainThread newrelic_plugin_agent.plugins.base            finish                    L140   : PostgreSQL poll successful, completed in 0.03 seconds
INFO       2016-07-29 10:29:58,403 12295  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L220   : Sending 77 metrics to NewRelic
INFO       2016-07-29 10:29:58,502 12295  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.13 seconds, next wake in 59 seconds
```

However, I'm not able to see any charts on the plugin page:
<img width="1324" alt="3" src="https://cloud.githubusercontent.com/assets/1825787/17251709/e0e78ca0-5577-11e6-86d2-9c5cb2fbf4ae.png">

Any ideas?

**Comment by ghost** [comment]
These instructions and samples are horrendously lacking.  I have done the options several different ways to Sunday and none result in the plugin working.

Error log repeatedly is:

INFO       2016-11-17 18:57:08,377 2675   MainProcess     MainThread newrelic_plugin_agent.agent                   **init**                  L55    : Agent v1.3.0 initialized, Linux-3.13.0-71-generic-x86_64-with-glibc2.4 (Ubuntu 14.04 trusty) CPython v2.7.6
INFO       2016-11-17 18:57:08,398 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: name
ERROR      2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin name not available
INFO       2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: port
ERROR      2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin port not available
INFO       2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: host
ERROR      2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin host not available
INFO       2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: path
ERROR      2016-11-17 18:57:08,399 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin path not available
INFO       2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: scheme
ERROR      2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin scheme not available
INFO       2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: newrelic_api_timeout
ERROR      2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin newrelic_api_timeout not available
INFO       2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: verify_ssl_cert
ERROR      2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin verify_ssl_cert not available
WARNING    2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L217   : No metrics to send to NewRelic this interval
INFO       2016-11-17 18:57:08,400 2684   MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.00 seconds, next wake in 59 seconds

My settings are (redacted, of course):

Application:
  license_key: cdfc2e5ec64a76e6cb25ed1b2797b8a8e2afbc1c
  poll_interval: 60
  #newrelic_api_timeout: 10
  #proxy: http://localhost:8080

  apache_httpd:
     -  name: www.mydomain.com
        scheme: https
        host: localhost
        port: 443
        path: /server-status
        verify_ssl_cert: true
     -  name: sub.mydomain.com
        scheme: https
        host: localhost
        port: 443
        path: /server-status
        verify_ssl_cert: true

How in the heck are some few people getting this to work?
